# Generated by Django 4.2.6 on 2023-12-18 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("omni_catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="omnibus",
            old_name="omnibus_format",
            new_name="format",
        ),
    ]
