# Generated by Django 4.2.6 on 2023-12-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_catalog", "0002_rename_omnibus_format_omnibus_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="omnibus",
            name="foc_date",
        ),
        migrations.RemoveField(
            model_name="omnibus",
            name="onsale_date",
        ),
        migrations.RemoveField(
            model_name="omnibus",
            name="print_price",
        ),
        migrations.RemoveField(
            model_name="omnibus",
            name="series_name",
        ),
        migrations.RemoveField(
            model_name="omnibus",
            name="thumbnail_path",
        ),
        migrations.AddField(
            model_name="omnibus",
            name="collected_issues",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="omnibus",
            name="collections",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="omnibus",
            name="dates",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="omnibus",
            name="prices",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="omnibus",
            name="series",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="omnibus",
            name="thumbnail",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="omnibus",
            name="variants",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="characters",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="creators",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="events",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="images",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="stories",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="text_objects",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="urls",
            field=models.JSONField(default={}),
        ),
    ]
