# Generated by Django 4.2.6 on 2023-12-20 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("omni_catalog", "0004_alter_omnibus_characters_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="omnibus",
            unique_together=set(),
        ),
    ]
