# Generated by Django 4.2.6 on 2023-12-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omni_catalog", "0005_alter_omnibus_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="omnibus",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="issn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="omnibus",
            name="variant_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
